### ISSUE TITLE
"Permission denied" error while running `fab vagrant highstate`

### ISSUE THREAD

**Issue by tobiasmcnulty** [caktus/django-project-template#113]
[33.33.33.10] out: ----------
    [33.33.33.10] out:           ID: syncdb
    [33.33.33.10] out:     Function: cmd.run
    [33.33.33.10] out:         Name: /var/www/myvoice/manage.sh syncdb --noinput
    [33.33.33.10] out:       Result: False
    [33.33.33.10] out:      Comment: Command "/var/www/myvoice/manage.sh syncdb --noinput" run
    [33.33.33.10] out:      Changes:   
    [33.33.33.10] out:               ----------
    [33.33.33.10] out:               pid:
    [33.33.33.10] out:                   809
    [33.33.33.10] out:               retcode:
    [33.33.33.10] out:                   1
    [33.33.33.10] out:               stderr:
    [33.33.33.10] out:                   Traceback (most recent call last):
    [33.33.33.10] out:                     File "/var/www/myvoice/source/manage.py", line 10, in <module>
    [33.33.33.10] out:                       execute_from_command_line(sys.argv)
    [33.33.33.10] out:                     File "/var/www/myvoice/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    [33.33.33.10] out:                       utility.execute()
    [33.33.33.10] out:                     File "/var/www/myvoice/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    [33.33.33.10] out:                       self.fetch_command(subcommand).run_from_argv(self.argv)
    [33.33.33.10] out:                     File "/var/www/myvoice/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 261, in fetch_command
    [33.33.33.10] out:                       commands = get_commands()
    [33.33.33.10] out:                     File "/var/www/myvoice/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 107, in get_commands
    [33.33.33.10] out:                       apps = settings.INSTALLED_APPS
    [33.33.33.10] out:                     File "/var/www/myvoice/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    [33.33.33.10] out:                       self._setup(name)
    [33.33.33.10] out:                     File "/var/www/myvoice/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 50, in _setup
    [33.33.33.10] out:                       self._configure_logging()
    [33.33.33.10] out:                     File "/var/www/myvoice/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 80, in _configure_logging
    [33.33.33.10] out:                       logging_config_func(self.LOGGING)
    [33.33.33.10] out:                     File "/usr/lib/python2.7/logging/config.py", line 777, in dictConfig
    [33.33.33.10] out:                       dictConfigClass(config).configure()
    [33.33.33.10] out:                     File "/usr/lib/python2.7/logging/config.py", line 575, in configure
    [33.33.33.10] out:                       '%r: %s' % (name, e))
    [33.33.33.10] out:                   ValueError: Unable to configure handler 'file': [Errno 13] Permission denied: '/vagrant/myvoice.log'
    [33.33.33.10] out:               stdout:
    [33.33.33.10] out:                   
    [33.33.33.10] out: ----------

**Comment by mlavin** [comment]
#155 makes the change for Vagrant to use production-like settings and requirements. Closing this issue.
