### ISSUE TITLE
Newly added pip package doesn't get 'seen' first time

### ISSUE THREAD

**Issue by vkurup** [caktus/django-project-template#197]
I don't currently have time to investigate, but opening this in case someone else sees similar behavior.

This is on a very recent project, using latest django-project-template and margarita 1.0.3

We added django-bread to our requirements:

```
git+git://github.com/caktus/django_bread@0.2.3#egg=django_bread
  django-filter==0.10.0
  django-vanilla-views==1.0.4
```
and to our INSTALLED_APPS.

On the first deploy, I got this error:

```
out: ----------
out:           ID: collectstatic
out:     Function: cmd.run
out:         Name: /var/www/projname/manage.sh collectstatic --noinput
out:       Result: False
out:      Comment: Command "/var/www/projname/manage.sh collectstatic --noinput" run
out:      Started: 18:46:01.886101
out:     Duration: 563.743 ms
out:      Changes:   
out:               ----------
out:               pid:
out:                   2012
out:               retcode:
out:                   1
out:               stderr:
out:                   Traceback (most recent call last):
out:                     File "/var/www/projname/source/manage.py", line 10, in <module>
out:                       execute_from_command_line(sys.argv)
out:                     File "/var/www/projname/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
out:                       utility.execute()
out:                     File "/var/www/projname/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute
out:                       django.setup()
out:                     File "/var/www/projname/env/lib/python3.4/site-packages/django/__init__.py", line 21, in setup
out:                       apps.populate(settings.INSTALLED_APPS)
out:                     File "/var/www/projname/env/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
out:                       app_config = AppConfig.create(entry)
out:                     File "/var/www/projname/env/lib/python3.4/site-packages/django/apps/config.py", line 87, in create
out:                       module = import_module(entry)
out:                     File "/var/www/projname/env/lib/python3.4/importlib/__init__.py", line 109, in import_module
out:                       return _bootstrap._gcd_import(name[level:], package, level)
out:                     File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
out:                     File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
out:                     File "<frozen importlib._bootstrap>", line 2201, in _find_and_load_unlocked
out:                   ImportError: No module named 'bread'
out:               stdout:
```

I deployed immediately again and it succeeded. Here's the full paste: https://portal.caktusgroup.com/paste/UbJVDY/ 

It makes me think there's a dependency problem, but I couldn't identify one.

**Comment by dpoirier** [comment]
Likely fixed by https://github.com/caktus/margarita/pull/68

**Comment by vkurup** [comment]
Yes, I think that will fix this.

Here's the relevant portion of the paste, with the irrelevant portions elided:

```
[45.79.194.250] out:   Name: /var/www/ucare4life/source - Function: file.directory - Result: Clean
...
[45.79.194.250] out:   Name: /var/www/ucare4life/env - Function: virtualenv.managed - Result: Clean
[45.79.194.250] out:   Name: pip_requirements - Function: pip.installed - Result: Changed
...
[45.79.194.250] out:   Name: git@github.com:caktus/ucare4life.git - Function: git.latest - Result: Changed
```

The `file.directory` state runs, then `pip install` runs, and then git updates the source code with the new requirements. The pip state should run after the git update and caktus/margarita#68 will achieve that.
